/* ===== COMPREHENSIVE INDIAN WEDDING CATERING MENU DATA ===== */

const MENU_DATA = {
  categories: [
    { id: "welcome-drinks", name: "Welcome Drinks", icon: "🥤" },
    { id: "mocktails", name: "Mocktails", icon: "🍹" },
    { id: "soups", name: "Soups", icon: "🍲" },
    { id: "salads", name: "Salads", icon: "🥗" },
    { id: "chaats", name: "Chaats & Snacks", icon: "🥔" },
    { id: "south-indian", name: "South Indian", icon: "🫓" },
    { id: "north-indian", name: "North Indian", icon: "🍛" },
    { id: "biryani", name: "Biryani", icon: "🍚" },
    { id: "dal", name: "Dal & Lentils", icon: "🫘" },
    { id: "paneer", name: "Paneer Specials", icon: "🧀" },
    { id: "vegetables", name: "Vegetables", icon: "🥕" },
    { id: "bread", name: "Indian Bread", icon: "🍞" },
    { id: "starters", name: "Starters", icon: "🍖" },
    { id: "tandoor", name: "Tandoor", icon: "🔥" },
    { id: "seafood", name: "Seafood", icon: "🦐" },
    { id: "desserts", name: "Desserts", icon: "🍰" },
    { id: "sweets", name: "Sweets", icon: "🧁" },
    { id: "beverages", name: "Beverages", icon: "☕" },
    { id: "kids", name: "Kids Menu", icon: "👶" },
    { id: "jain", name: "Jain Menu", icon: "🌱" },
  ],

  dishes: [
    // Welcome Drinks
    {
      id: 1,
      name: "Shikanji",
      category: "welcome-drinks",
      price: 45,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      popular: true,
      description: "Traditional lemon mint juice",
    },
    {
      id: 2,
      name: "Jaljeera",
      category: "welcome-drinks",
      price: 45,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 2,
      description: "Spiced cumin water",
    },
    {
      id: 3,
      name: "Buttermilk",
      category: "welcome-drinks",
      price: 40,
      veg: true,
      jain: true,
      spicy: 1,
      description: "Traditional yogurt drink",
    },
    {
      id: 4,
      name: "Rose Sherbet",
      category: "welcome-drinks",
      price: 50,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 0,
      popular: true,
      description: "Sweet rose flavored drink",
    },
    {
      id: 5,
      name: "Lassi Mango",
      category: "welcome-drinks",
      price: 60,
      veg: true,
      jain: true,
      spicy: 0,
      description: "Yogurt based mango drink",
    },

    // Mocktails
    {
      id: 6,
      name: "Virgin Mojito",
      category: "mocktails",
      price: 80,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 0,
      popular: true,
      description: "Mint lime refresher",
    },
    {
      id: 7,
      name: "Cucumber Mint Cooler",
      category: "mocktails",
      price: 75,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 0,
      description: "Refreshing summer drink",
    },
    {
      id: 8,
      name: "Strawberry Smoothie",
      category: "mocktails",
      price: 85,
      veg: true,
      jain: true,
      spicy: 0,
      description: "Fresh fruit smoothie",
    },
    {
      id: 9,
      name: "Mango Lassi Mocktail",
      category: "mocktails",
      price: 90,
      veg: true,
      jain: true,
      spicy: 0,
      description: "Premium mango yogurt drink",
    },
    {
      id: 10,
      name: "Pineapple Mint Fizz",
      category: "mocktails",
      price: 75,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 0,
      description: "Tropical fizzy drink",
    },

    // Soups
    {
      id: 11,
      name: "Tomato Shorba",
      category: "soups",
      price: 60,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 2,
      popular: true,
      description: "Traditional spiced tomato soup",
    },
    {
      id: 12,
      name: "Mulligatawny Soup",
      category: "soups",
      price: 70,
      veg: false,
      jain: false,
      spicy: 3,
      description: "Lentil and meat soup",
    },
    {
      id: 13,
      name: "Corn Soup",
      category: "soups",
      price: 65,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      popular: true,
      description: "Creamy corn soup",
    },
    {
      id: 14,
      name: "Chicken Clear Soup",
      category: "soups",
      price: 75,
      veg: false,
      jain: false,
      spicy: 2,
      description: "Light chicken broth",
    },
    {
      id: 15,
      name: "Mushroom Soup",
      category: "soups",
      price: 70,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      description: "Creamy mushroom soup",
    },
    {
      id: 16,
      name: "Hot & Sour Soup",
      category: "soups",
      price: 80,
      veg: false,
      jain: false,
      spicy: 4,
      description: "Spicy tangy Asian soup",
    },

    // Salads
    {
      id: 17,
      name: "Kachumber Salad",
      category: "salads",
      price: 55,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      popular: true,
      description: "Fresh vegetable salad",
    },
    {
      id: 18,
      name: "Greek Salad",
      category: "salads",
      price: 65,
      veg: true,
      jain: false,
      spicy: 0,
      description: "Feta cheese and vegetable",
    },
    {
      id: 19,
      name: "Coleslaw",
      category: "salads",
      price: 50,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 0,
      description: "Cabbage and carrot salad",
    },
    {
      id: 20,
      name: "Quinoa Salad",
      category: "salads",
      price: 90,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 0,
      popular: true,
      description: "Healthy superfood salad",
    },
    {
      id: 21,
      name: "Chicken Salad",
      category: "salads",
      price: 95,
      veg: false,
      jain: false,
      spicy: 1,
      description: "Grilled chicken with greens",
    },

    // Chaats
    {
      id: 22,
      name: "Samosa",
      category: "chaats",
      price: 30,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 2,
      popular: true,
      description: "Fried pastry with potato filling",
    },
    {
      id: 23,
      name: "Chaat Papdi",
      category: "chaats",
      price: 40,
      veg: true,
      jain: true,
      spicy: 3,
      description: "Crispy papdi with chutneys",
    },
    {
      id: 24,
      name: "Pani Puri",
      category: "chaats",
      price: 35,
      veg: true,
      jain: true,
      spicy: 4,
      popular: true,
      description: "Hollow puri with spiced water",
    },
    {
      id: 25,
      name: "Sev Tameta",
      category: "chaats",
      price: 45,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 2,
      description: "Potato with gram flour noodles",
    },
    {
      id: 26,
      name: "Aloo Tikki",
      category: "chaats",
      price: 40,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 2,
      description: "Fried potato patty",
    },
    {
      id: 27,
      name: "Bhelpuri",
      category: "chaats",
      price: 40,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 2,
      description: "Mixed puffed rice snack",
    },
    {
      id: 28,
      name: "Dahi Bhalle",
      category: "chaats",
      price: 45,
      veg: true,
      jain: false,
      spicy: 0,
      description: "Lentil fritters in yogurt",
    },

    // South Indian
    {
      id: 29,
      name: "Idli",
      category: "south-indian",
      price: 50,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 0,
      popular: true,
      description: "Steamed rice cakes",
    },
    {
      id: 30,
      name: "Dosa",
      category: "south-indian",
      price: 60,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      popular: true,
      description: "Crispy fermented rice crepe",
    },
    {
      id: 31,
      name: "Uttapam",
      category: "south-indian",
      price: 65,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      description: "Thick rice pancake with toppings",
    },
    {
      id: 32,
      name: "Medhu Vada",
      category: "south-indian",
      price: 55,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      popular: true,
      description: "Soft lentil donuts",
    },
    {
      id: 33,
      name: "Sambar",
      category: "south-indian",
      price: 65,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 2,
      description: "Spiced vegetable stew",
    },
    {
      id: 34,
      name: "Rasam",
      category: "south-indian",
      price: 60,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 2,
      description: "Tangy tamarind soup",
    },
    {
      id: 35,
      name: "Coconut Chutney",
      category: "south-indian",
      price: 40,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 0,
      description: "Fresh coconut paste",
    },

    // North Indian
    {
      id: 36,
      name: "Butter Chicken",
      category: "north-indian",
      price: 280,
      veg: false,
      jain: false,
      spicy: 2,
      popular: true,
      description: "Chicken in creamy tomato sauce",
    },
    {
      id: 37,
      name: "Rogan Josh",
      category: "north-indian",
      price: 300,
      veg: false,
      jain: false,
      spicy: 3,
      description: "Aromatic meat curry",
    },
    {
      id: 38,
      name: "Nihari",
      category: "north-indian",
      price: 320,
      veg: false,
      jain: false,
      spicy: 3,
      popular: true,
      description: "Slow cooked meat stew",
    },
    {
      id: 39,
      name: "Chole Bhature",
      category: "north-indian",
      price: 120,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 2,
      popular: true,
      description: "Chickpea curry with fried bread",
    },
    {
      id: 40,
      name: "Aloo Prantha",
      category: "north-indian",
      price: 80,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      description: "Potato stuffed flatbread",
    },

    // Biryani
    {
      id: 41,
      name: "Chicken Biryani",
      category: "biryani",
      price: 240,
      veg: false,
      jain: false,
      spicy: 2,
      popular: true,
      description: "Fragrant rice with tender chicken",
    },
    {
      id: 42,
      name: "Mutton Biryani",
      category: "biryani",
      price: 280,
      veg: false,
      jain: false,
      spicy: 3,
      popular: true,
      description: "Royal meat biryani",
    },
    {
      id: 43,
      name: "Vegetable Biryani",
      category: "biryani",
      price: 180,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 2,
      description: "Mixed vegetable rice",
    },
    {
      id: 44,
      name: "Paneer Biryani",
      category: "biryani",
      price: 200,
      veg: true,
      jain: true,
      spicy: 2,
      description: "Cottage cheese biryani",
    },
    {
      id: 45,
      name: "Prawn Biryani",
      category: "biryani",
      price: 320,
      veg: false,
      jain: false,
      spicy: 2,
      description: "Seafood biryani",
    },
    {
      id: 46,
      name: "Hyderabadi Biryani",
      category: "biryani",
      price: 250,
      veg: false,
      jain: false,
      spicy: 2,
      description: "Traditional Hyderabadi style",
    },

    // Dal
    {
      id: 47,
      name: "Dal Makhani",
      category: "dal",
      price: 120,
      veg: true,
      jain: true,
      spicy: 1,
      popular: true,
      description: "Creamy black lentils",
    },
    {
      id: 48,
      name: "Toor Dal Fry",
      category: "dal",
      price: 100,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      description: "Tempered split pigeon peas",
    },
    {
      id: 49,
      name: "Masoor Dal",
      category: "dal",
      price: 90,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      description: "Red lentil preparation",
    },
    {
      id: 50,
      name: "Chana Dal",
      category: "dal",
      price: 95,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      description: "Split chickpea lentils",
    },
    {
      id: 51,
      name: "Mixed Dal",
      category: "dal",
      price: 110,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      description: "Three lentil combination",
    },

    // Paneer
    {
      id: 52,
      name: "Paneer Butter Masala",
      category: "paneer",
      price: 240,
      veg: true,
      jain: true,
      spicy: 2,
      popular: true,
      description: "Soft paneer in creamy sauce",
    },
    {
      id: 53,
      name: "Paneer Tikka Masala",
      category: "paneer",
      price: 250,
      veg: true,
      jain: true,
      spicy: 2,
      description: "Grilled paneer in tomato gravy",
    },
    {
      id: 54,
      name: "Kadai Paneer",
      category: "paneer",
      price: 230,
      veg: true,
      jain: true,
      spicy: 3,
      popular: true,
      description: "Paneer with bell peppers",
    },
    {
      id: 55,
      name: "Shahi Paneer",
      category: "paneer",
      price: 260,
      veg: true,
      jain: true,
      spicy: 1,
      description: "Rich creamy paneer curry",
    },
    {
      id: 56,
      name: "Paneer Do Pyaza",
      category: "paneer",
      price: 220,
      veg: true,
      jain: true,
      spicy: 2,
      description: "Paneer with double onions",
    },
    {
      id: 57,
      name: "Palak Paneer",
      category: "paneer",
      price: 210,
      veg: true,
      jain: true,
      spicy: 1,
      popular: true,
      description: "Spinach and paneer curry",
    },
    {
      id: 58,
      name: "Mater Paneer",
      category: "paneer",
      price: 200,
      veg: true,
      jain: true,
      spicy: 1,
      description: "Paneer with green peas",
    },

    // Vegetables
    {
      id: 59,
      name: "Aloo Gobi",
      category: "vegetables",
      price: 140,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 2,
      popular: true,
      description: "Potato and cauliflower curry",
    },
    {
      id: 60,
      name: "Baingan Bharta",
      category: "vegetables",
      price: 130,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 2,
      description: "Smoky eggplant mash",
    },
    {
      id: 61,
      name: "Mushroom Curry",
      category: "vegetables",
      price: 150,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      description: "Creamy mushroom preparation",
    },
    {
      id: 62,
      name: "Broccoli Chilli",
      category: "vegetables",
      price: 140,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 3,
      description: "Stir-fried broccoli",
    },
    {
      id: 63,
      name: "Mix Vegetable Curry",
      category: "vegetables",
      price: 130,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      popular: true,
      description: "Seasonal mixed vegetables",
    },
    {
      id: 64,
      name: "Methi Fenugreek",
      category: "vegetables",
      price: 120,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      description: "Fenugreek leaves curry",
    },
    {
      id: 65,
      name: "Lauki Chikhalwali",
      category: "vegetables",
      price: 100,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      description: "Bottle gourd curry",
    },

    // Bread
    {
      id: 66,
      name: "Naan",
      category: "bread",
      price: 40,
      veg: true,
      jain: true,
      spicy: 0,
      popular: true,
      description: "Traditional tandoor bread",
    },
    {
      id: 67,
      name: "Garlic Naan",
      category: "bread",
      price: 50,
      veg: true,
      jain: true,
      spicy: 0,
      popular: true,
      description: "Naan with garlic butter",
    },
    {
      id: 68,
      name: "Butter Naan",
      category: "bread",
      price: 50,
      veg: true,
      jain: true,
      spicy: 0,
      description: "Buttered naan",
    },
    {
      id: 69,
      name: "Cheese Naan",
      category: "bread",
      price: 60,
      veg: true,
      jain: true,
      spicy: 0,
      description: "Naan stuffed with cheese",
    },
    {
      id: 70,
      name: "Roti",
      category: "bread",
      price: 30,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 0,
      popular: true,
      description: "Whole wheat flatbread",
    },
    {
      id: 71,
      name: "Paratha",
      category: "bread",
      price: 50,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 0,
      description: "Layered flatbread",
    },
    {
      id: 72,
      name: "Puri",
      category: "bread",
      price: 40,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 0,
      description: "Deep-fried bread",
    },
    {
      id: 73,
      name: "Bhatura",
      category: "bread",
      price: 60,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 0,
      description: "Large fried bread",
    },

    // Starters
    {
      id: 74,
      name: "Paneer Tikka",
      category: "starters",
      price: 180,
      veg: true,
      jain: true,
      spicy: 2,
      popular: true,
      description: "Grilled cottage cheese",
    },
    {
      id: 75,
      name: "Chicken Tikka",
      category: "starters",
      price: 220,
      veg: false,
      jain: false,
      spicy: 2,
      popular: true,
      description: "Marinated grilled chicken",
    },
    {
      id: 76,
      name: "Seekh Kebab",
      category: "starters",
      price: 240,
      veg: false,
      jain: false,
      spicy: 2,
      description: "Minced meat kebab",
    },
    {
      id: 77,
      name: "Sheekh Paneer",
      category: "starters",
      price: 200,
      veg: true,
      jain: true,
      spicy: 2,
      description: "Grilled paneer skewer",
    },
    {
      id: 78,
      name: "Tandoori Fish",
      category: "starters",
      price: 280,
      veg: false,
      jain: false,
      spicy: 2,
      description: "Tandoor grilled fish",
    },
    {
      id: 79,
      name: "Malai Tikka",
      category: "starters",
      price: 200,
      veg: true,
      jain: true,
      spicy: 1,
      description: "Creamy yogurt tikka",
    },
    {
      id: 80,
      name: "Vegetable Kebab",
      category: "starters",
      price: 150,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      description: "Mixed vegetable skewer",
    },

    // Tandoor
    {
      id: 81,
      name: "Tandoori Chicken",
      category: "tandoor",
      price: 280,
      veg: false,
      jain: false,
      spicy: 2,
      popular: true,
      description: "Traditional tandoor chicken",
    },
    {
      id: 82,
      name: "Tandoori Prawn",
      category: "tandoor",
      price: 350,
      veg: false,
      jain: false,
      spicy: 2,
      description: "Spiced tandoor prawns",
    },
    {
      id: 83,
      name: "Tandoori Fish Tikka",
      category: "tandoor",
      price: 320,
      veg: false,
      jain: false,
      spicy: 2,
      description: "Fish pieces tandoor grilled",
    },
    {
      id: 84,
      name: "Tandoori Mushroom",
      category: "tandoor",
      price: 180,
      veg: true,
      jain: true,
      spicy: 1,
      description: "Marinated tandoor mushrooms",
    },
    {
      id: 85,
      name: "Tandoori Vegetables",
      category: "tandoor",
      price: 160,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      description: "Grilled seasonal vegetables",
    },

    // Seafood
    {
      id: 86,
      name: "Butter Garlic Crab",
      category: "seafood",
      price: 400,
      veg: false,
      jain: false,
      spicy: 2,
      popular: true,
      description: "Crab in buttery garlic sauce",
    },
    {
      id: 87,
      name: "Fish Curry",
      category: "seafood",
      price: 320,
      veg: false,
      jain: false,
      spicy: 2,
      description: "Traditional fish gravy",
    },
    {
      id: 88,
      name: "Prawn Curry",
      category: "seafood",
      price: 360,
      veg: false,
      jain: false,
      spicy: 2,
      description: "Succulent prawn preparation",
    },
    {
      id: 89,
      name: "Garlic Butter Prawns",
      category: "seafood",
      price: 380,
      veg: false,
      jain: false,
      spicy: 1,
      description: "Butter garlic prawns",
    },
    {
      id: 90,
      name: "Chilli Crab",
      category: "seafood",
      price: 420,
      veg: false,
      jain: false,
      spicy: 4,
      description: "Spicy chilli crab",
    },

    // Desserts
    {
      id: 91,
      name: "Gulab Jamun",
      category: "desserts",
      price: 80,
      veg: true,
      jain: true,
      spicy: 0,
      popular: true,
      description: "Milk solids in sugar syrup",
    },
    {
      id: 92,
      name: "Kheer",
      category: "desserts",
      price: 70,
      veg: true,
      jain: true,
      spicy: 0,
      popular: true,
      description: "Rice pudding with milk",
    },
    {
      id: 93,
      name: "Rasmalai",
      category: "desserts",
      price: 90,
      veg: true,
      jain: true,
      spicy: 0,
      description: "Soft cheese in cream",
    },
    {
      id: 94,
      name: "Jalebi",
      category: "desserts",
      price: 60,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 0,
      description: "Spiraled pretzel dessert",
    },
    {
      id: 95,
      name: "Falooda",
      category: "desserts",
      price: 100,
      veg: true,
      jain: true,
      spicy: 0,
      description: "Layered dessert with vermicelli",
    },

    // Sweets
    {
      id: 96,
      name: "Halwa",
      category: "sweets",
      price: 70,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 0,
      popular: true,
      description: "Semolina pudding",
    },
    {
      id: 97,
      name: "Barfi",
      category: "sweets",
      price: 60,
      veg: true,
      jain: true,
      spicy: 0,
      description: "Fudgy milk sweet",
    },
    {
      id: 98,
      name: "Laddu",
      category: "sweets",
      price: 50,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 0,
      description: "Round sesame ball",
    },
    {
      id: 99,
      name: "Peda",
      category: "sweets",
      price: 55,
      veg: true,
      jain: true,
      spicy: 0,
      description: "Condensed milk sweet",
    },
    {
      id: 100,
      name: "Burfi",
      category: "sweets",
      price: 65,
      veg: true,
      jain: true,
      spicy: 0,
      description: "Diamond shaped sweet",
    },

    // Beverages
    {
      id: 101,
      name: "Indian Tea",
      category: "beverages",
      price: 30,
      veg: true,
      jain: true,
      spicy: 0,
      popular: true,
      description: "Traditional masala chai",
    },
    {
      id: 102,
      name: "Coffee",
      category: "beverages",
      price: 40,
      veg: true,
      jain: true,
      spicy: 0,
      description: "Fresh filter coffee",
    },
    {
      id: 103,
      name: "Iced Tea",
      category: "beverages",
      price: 50,
      veg: true,
      jain: true,
      spicy: 0,
      description: "Chilled tea with lemon",
    },
    {
      id: 104,
      name: "Fresh Juices",
      category: "beverages",
      price: 60,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 0,
      description: "Seasonal fruit juices",
    },
    {
      id: 105,
      name: "Smoothies",
      category: "beverages",
      price: 80,
      veg: true,
      jain: true,
      spicy: 0,
      description: "Fruit and yogurt smoothies",
    },

    // Kids Menu
    {
      id: 106,
      name: "Butter Noodles",
      category: "kids",
      price: 100,
      veg: true,
      jain: true,
      spicy: 0,
      popular: true,
      description: "Mild buttered noodles",
    },
    {
      id: 107,
      name: "Mac n Cheese",
      category: "kids",
      price: 110,
      veg: true,
      jain: true,
      spicy: 0,
      description: "Creamy cheese pasta",
    },
    {
      id: 108,
      name: "Chicken Nuggets",
      category: "kids",
      price: 130,
      veg: false,
      jain: false,
      spicy: 0,
      description: "Breaded chicken pieces",
    },
    {
      id: 109,
      name: "Veg Pulao",
      category: "kids",
      price: 90,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 0,
      description: "Simple rice with vegetables",
    },

    // Jain Menu
    {
      id: 110,
      name: "Jain Dal Fry",
      category: "jain",
      price: 100,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      description: "Jain compliant lentils",
    },
    {
      id: 111,
      name: "Jain Biryani",
      category: "jain",
      price: 150,
      veg: true,
      jain: true,
      vegan: true,
      spicy: 1,
      description: "Jain vegetable biryani",
    },
    {
      id: 112,
      name: "Jain Paneer Curry",
      category: "jain",
      price: 200,
      veg: true,
      jain: true,
      spicy: 1,
      description: "Jain paneer preparation",
    },
  ],

  menuTemplates: [
    {
      name: "Budget Menu",
      guestCount: 100,
      perPlatePrice: 250,
      dishes: [1, 22, 29, 36, 47, 52, 66, 91],
    },
    {
      name: "Silver Package",
      guestCount: 100,
      perPlatePrice: 500,
      dishes: [2, 23, 30, 37, 48, 53, 67, 92],
    },
    {
      name: "Gold Package",
      guestCount: 100,
      perPlatePrice: 750,
      dishes: [3, 24, 31, 38, 49, 54, 68, 93],
    },
    {
      name: "Premium Package",
      guestCount: 100,
      perPlatePrice: 1000,
      dishes: [4, 25, 32, 41, 55, 69, 74, 94],
    },
    {
      name: "Royal Package",
      guestCount: 100,
      perPlatePrice: 1500,
      dishes: [5, 26, 33, 42, 56, 70, 75, 95],
    },
    {
      name: "Luxury Package",
      guestCount: 100,
      perPlatePrice: 2000,
      dishes: [6, 27, 34, 43, 57, 71, 81, 96],
    },
  ],

  eventTypes: [
    { id: "wedding", name: "Wedding Reception" },
    { id: "engagement", name: "Engagement Party" },
    { id: "haldi", name: "Haldi Ceremony" },
    { id: "mehendi", name: "Mehendi Celebration" },
    { id: "sangeet", name: "Sangeet Evening" },
    { id: "corporate", name: "Corporate Event" },
    { id: "birthday", name: "Birthday Party" },
    { id: "anniversary", name: "Anniversary Celebration" },
    { id: "housewarming", name: "Housewarming" },
    { id: "custom", name: "Custom Event" },
  ],

  pricing: {
    gstRate: 0.05,
    deliveryCharge: 50,
    serviceCharge: 0.1,
  },
};

// Smart Rules for Menu Building
const SMART_RULES = {
  maxDesserts: 2,
  maxVegetables: 3,
  maxBread: 2,
  maxRice: 1,
  maxDal: 1,
  maxStarters: 2,
  unlimitedBeverages: true,
  unlimitedSnacks: true,
};

// Export for use in modules
if (typeof module !== "undefined" && module.exports) {
  module.exports = { MENU_DATA, SMART_RULES };
}
